baseURL = 'https://freeresumescanner.com'
languageCode = 'en-us'
title = 'Free Resume Scanner - Free Resume Scans for Life'
theme = "free-resume-scanner-theme"

[taxonomies]
  tag = "tags"
[params]
  dateFormat = "Jan 2, 2006"
  homeText = "You just made a Hugo blog from scratch."
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false