baseURL = 'https://freeresumescanner.com'
languageCode = 'en-us'
title = 'Free Resume Scanner - Free Resume Scans for Life'
theme = "free-resume-scanner-theme"

[taxonomies]
  tag = "tags"
[params]
  dateFormat = "Jan 2, 2022"
  homeText = "a new theme has been spotted!"